# Generated by Django 4.2.16 on 2026-06-05 07:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_password_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_requests', to='accounts.organization')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_requests', to='accounts.membership')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_password_requests', to='accounts.membership')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', 'status'], name='accounts_pa_org_id_03ade2_idx')],
            },
        ),
    ]
