# Generated by Django 4.2.16 on 2026-06-03 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('logo', 'Logo'), ('cover', 'Cover'), ('banner', 'Banner')], max_length=10)),
                ('owner_type', models.CharField(blank=True, choices=[('menu_item', 'Menu item'), ('category', 'Category'), ('restaurant', 'Restaurant')], max_length=16)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('bucket', models.CharField(max_length=120)),
                ('key', models.CharField(help_text='Object-storage key (NOT a data-URL).', max_length=500)),
                ('poster_key', models.CharField(blank=True, max_length=500)),
                ('renditions', models.JSONField(blank=True, default=dict, help_text='e.g. {"1080": "<key>", "720": "<key>"}')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('bytes', models.BigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('blurhash', models.CharField(blank=True, help_text='LQIP placeholder.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant_id', 'owner_type', 'owner_id'], name='assets_medi_restaur_a0ec59_idx'), models.Index(fields=['restaurant_id', 'status'], name='assets_medi_restaur_82dc8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetRendition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('variant', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.BigIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='assets.mediaasset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetrendition',
            constraint=models.UniqueConstraint(fields=('asset', 'variant'), name='uniq_asset_variant'),
        ),
    ]
