# Generated by Django 4.2.16 on 2026-06-03 05:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('org_id', models.UUIDField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('base_minor', models.IntegerField()),
                ('gst_minor', models.IntegerField()),
                ('total_minor', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('failed', 'Failed')], default='due', max_length=8)),
                ('razorpay_id', models.CharField(blank=True, max_length=64, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('package', models.CharField(choices=[('web-menu', 'Web Menu'), ('classic', 'Classic'), ('cinematic', 'Cinematic'), ('signature', 'Signature')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('renewal_at', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('gst_pct', models.IntegerField(default=18)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_event_id', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.invoice')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription'),
        ),
    ]
