# Generated by Django 4.2.16 on 2026-06-03 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Bronze', max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('lifetime_spend_minor', models.BigIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('party_size', models.PositiveSmallIntegerField()),
                ('quoted_mins', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('seated', 'Seated'), ('left', 'Left')], default='waiting', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='crm.customer')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('party_size', models.PositiveSmallIntegerField()),
                ('at', models.DateTimeField()),
                ('table_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no-show', 'No-show')], default='booked', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='crm.customer')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('points_delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('adjust', 'Adjust'), ('expire', 'Expire')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('table_id', models.UUIDField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('routed_to_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant_id', '-created_at'], name='crm_feedbac_restaur_120f93_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('visits', models.IntegerField(default=0)),
                ('first_visit', models.DateTimeField(blank=True, null=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='crm.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('org_id', 'phone'), name='uniq_customer_org_phone'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['restaurant_id', 'at'], name='crm_reserva_restaur_b74a95_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyledger',
            index=models.Index(fields=['customer', '-created_at'], name='crm_loyalty_custome_c01b1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeroutlet',
            constraint=models.UniqueConstraint(fields=('customer', 'restaurant_id'), name='uniq_customer_outlet'),
        ),
    ]
