# Generated by Django 4.2.16 on 2026-06-05 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayGreeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('year', models.PositiveIntegerField()),
                ('channel', models.CharField(default='pending', max_length=20)),
                ('bonus_points', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_greetings', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='birthdaygreeting',
            constraint=models.UniqueConstraint(fields=('customer', 'year'), name='uniq_birthday_greeting_customer_year'),
        ),
    ]
