# Generated by Django 4.2.16 on 2026-06-04 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ordering', 'Ordering'), ('bill_requested', 'Bill requested'), ('closed', 'Closed'), ('abandoned', 'Abandoned')], default='open', max_length=16)),
                ('epoch', models.PositiveIntegerField(default=1)),
                ('order_confirmation_mode', models.CharField(choices=[('auto_fire', 'Auto fire'), ('leader', 'Leader'), ('waiter_confirm', 'Waiter confirm')], default='waiter_confirm', max_length=16)),
                ('party_size', models.PositiveSmallIntegerField(default=0)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('orderer', 'Orderer'), ('leader', 'Leader')], default='participant', max_length=12)),
                ('is_payer', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.customer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dining.diningsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='diningsession',
            name='leader_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dining.guestdevice'),
        ),
        migrations.AddField(
            model_name='diningsession',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ops.restauranttable'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal_minor', models.BigIntegerField(default=0)),
                ('tax_minor', models.BigIntegerField(default=0)),
                ('service_charge_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField(default=0)),
                ('paid_minor', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially paid'), ('settled', 'Settled'), ('void', 'Void'), ('disputed', 'Disputed')], default='open', max_length=16)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=80)),
                ('liable_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.customer')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tab', to='dining.diningsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='guestdevice',
            index=models.Index(fields=['session', 'role'], name='dining_gues_session_324368_idx'),
        ),
        migrations.AddIndex(
            model_name='guestdevice',
            index=models.Index(fields=['restaurant_id', 'last_seen'], name='dining_gues_restaur_52eaba_idx'),
        ),
        migrations.AddIndex(
            model_name='diningsession',
            index=models.Index(fields=['restaurant_id', 'status'], name='dining_dini_restaur_357d5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='diningsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'ordering', 'bill_requested'))), fields=('table',), name='uniq_live_session_per_table'),
        ),
    ]
