# Generated by Django 4.2.16 on 2026-06-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='check',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_order_id', ''), _negated=True), fields=('razorpay_order_id',), name='uniq_check_razorpay_order_id'),
        ),
    ]
