# Generated by Django 4.2.16 on 2026-06-05 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_check_uniq_check_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningsession',
            name='order_confirmation_mode',
            field=models.CharField(choices=[('auto_fire', 'Auto fire'), ('leader', 'Leader'), ('waiter_confirm', 'Waiter confirm')], default='leader', max_length=16),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('table_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('waiter', 'Call waiter'), ('water', 'Water'), ('bill', 'Bill'), ('assistance', 'Assistance'), ('cleanup', 'Cleanup')], default='waiter', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('claimed_by_id', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='dining.guestdevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='dining.diningsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant_id', 'status'], name='dining_serv_restaur_2fa323_idx'), models.Index(fields=['session', 'status'], name='dining_serv_session_e40569_idx')],
            },
        ),
    ]
