# Generated by Django 4.2.16 on 2026-06-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_alter_diningsession_order_confirmation_mode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
