// Download CURATED, high-quality free Pixabay clips at multiple resolutions for
// network-adaptive playback. Clips were hand-picked (brightness / motion /
// relevance / resolution / popularity) per surface — see the `why` notes in the
// curation pass. We download each at several heights WITHOUT re-encoding, so the
// quality is the source's native quality; the app picks a rendition by network.
//
// Usage:  npm run fetch:videos
// Output: public/assets/video/<key>-<height>.mp4  +  src/data/videoRenditions.ts
//
// No API key needed — these are public CDN URLs. The app falls back to posters
// for any rendition that fails to download.

import { mkdir, writeFile, access } from 'node:fs/promises'
import { constants } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const OUT_DIR = join(ROOT, 'public', 'assets', 'video')
const MANIFEST_TS = join(ROOT, 'src', 'data', 'videoRenditions.ts')

// surface key → { height: cdnUrl }. Heights are normalized buckets used by
// pickRendition (1080 / 720 / 360). 1080 is the quality ceiling for web — we skip
// the 4K renditions some clips offer (too heavy for a menu).
const cdn = (path, suffix) => `https://cdn.pixabay.com/video/${path}_${suffix}.mp4`

const CLIPS = {
  // hero — id 11620, bright gourmet plating, 20s, 1080p
  hero: { 1080: cdn('2017/08/29/11620-231571928', 'large'), 720: cdn('2017/08/29/11620-231571928', 'medium'), 360: cdn('2017/08/29/11620-231571928', 'tiny') },
  // beverages — id 2290, lemonade pour, 16s
  beverages: { 1080: cdn('2016/02/29/2290-157183576', 'large'), 720: cdn('2016/02/29/2290-157183576', 'medium'), 360: cdn('2016/02/29/2290-157183576', 'tiny') },
  // soups — id 11684, bright Thai broth bowl, 18s
  soups: { 1080: cdn('2017/08/30/11684-231758919', 'large'), 720: cdn('2017/08/30/11684-231758919', 'medium'), 360: cdn('2017/08/30/11684-231758919', 'tiny') },
  // quickbites — id 11674, crispy snack plate, 18s
  quickbites: { 1080: cdn('2017/08/30/11674-231758834', 'large'), 720: cdn('2017/08/30/11674-231758834', 'medium'), 360: cdn('2017/08/30/11674-231758834', 'tiny') },
  // italian — id 33256, spaghetti + fork, 10s
  italian: { 1080: cdn('2020/03/05/33256-396487978', 'large'), 720: cdn('2020/03/05/33256-396487978', 'medium'), 360: cdn('2020/03/05/33256-396487978', 'tiny') },
  // desserts — id 71743, chocolate over strawberry, 9s (source is 4K; take 1080/720)
  desserts: { 1080: cdn('2021/04/21/71743-539969557', 'small'), 720: cdn('2021/04/21/71743-539969557', 'tiny') },
  // svc-waiter — id 181546, server in restaurant, 4K source (take 1080/720).
  // Picked over fallback id 13018 on brightness (109 vs 93/255) + motion.
  waiter: { 1080: cdn('2023/09/21/181546-866999878', 'small'), 720: cdn('2023/09/21/181546-866999878', 'tiny') },
  // svc-water — id 95, water poured into glass, 16s
  water: { 1080: cdn('2015/08/08/95-135735410', 'large'), 720: cdn('2015/08/08/95-135735410', 'medium'), 360: cdn('2015/08/08/95-135735410', 'small') },
  // svc-bread — id 14239, fresh loaf sliced, 21s
  bread: { 1080: cdn('2018/02/10/14239-255658087', 'large'), 720: cdn('2018/02/10/14239-255658087', 'medium'), 360: cdn('2018/02/10/14239-255658087', 'tiny') },
}

async function exists(p) {
  try { await access(p, constants.F_OK); return true } catch { return false }
}

async function download(url, dest) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const buf = Buffer.from(await res.arrayBuffer())
  await writeFile(dest, buf)
  return buf.length
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true })
  console.log(`→ Saving renditions to ${OUT_DIR}\n`)

  const manifest = {} // key → [{ height, src }]
  let ok = 0, skipped = 0, failed = 0

  for (const [key, heights] of Object.entries(CLIPS)) {
    const got = []
    for (const [height, url] of Object.entries(heights)) {
      const file = `${key}-${height}.mp4`
      const dest = join(OUT_DIR, file)
      const src = `/assets/video/${file}`
      if (await exists(dest)) {
        got.push({ height: Number(height), src })
        skipped++
        continue
      }
      try {
        const bytes = await download(url, dest)
        got.push({ height: Number(height), src })
        console.log(`✓ ${file.padEnd(20)} ${(bytes / 1048576).toFixed(1)}MB`)
        ok++
      } catch (err) {
        console.warn(`✖ ${file.padEnd(20)} ${err instanceof Error ? err.message : String(err)}`)
        failed++
      }
    }
    if (got.length) manifest[key] = got.sort((a, b) => b.height - a.height)
  }

  // Emit a typed renditions manifest the app imports.
  const body =
    `// AUTO-GENERATED by scripts/fetch-videos.mjs — do not edit by hand.\n` +
    `import type { Rendition } from '../lib/pickRendition'\n\n` +
    `export const RENDITIONS: Record<string, Rendition[]> = ${JSON.stringify(manifest, null, 2)}\n`
  await writeFile(MANIFEST_TS, body)

  console.log(`\nDone — ${ok} downloaded, ${skipped} skipped, ${failed} failed.`)
  console.log(`Wrote ${MANIFEST_TS}`)
}

main().catch(err => { console.error(err); process.exit(1) })
