# Generated by Django 4.2.16 on 2026-06-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_identity_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='theme', serialize=False, to='accounts.restaurant')),
                ('ui_theme', models.CharField(choices=[('warm', 'Warm'), ('hybrid', 'Hybrid'), ('brutalist', 'Brutalist'), ('editorial', 'Editorial')], default='warm', max_length=20)),
                ('component_style', models.CharField(choices=[('classic', 'Classic'), ('motion', 'Motion'), ('spectacle', 'Spectacle')], default='classic', max_length=20)),
                ('media_mode', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=20)),
                ('token_overrides', models.JSONField(blank=True, default=dict, help_text='Partial ThemeTokens patch (colors/fonts).')),
                ('allow_customer_choice', models.BooleanField(default=False)),
                ('customer_choices', models.JSONField(blank=True, default=list, help_text='Subset of ui_themes a guest may pick.')),
                ('draft', models.JSONField(blank=True, default=dict, help_text='Unpublished working copy of the config.')),
                ('published', models.BooleanField(default=False)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('cover_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
