# Generated by Django 4.2.16 on 2026-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttheme',
            name='brand_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Brand color overrides: {primary, secondary, accent} as hex.'),
        ),
        migrations.AddField(
            model_name='restauranttheme',
            name='custom_font',
            field=models.JSONField(blank=True, default=dict, help_text='An imported font: {name, url} (woff2/woff).'),
        ),
        migrations.AddField(
            model_name='restauranttheme',
            name='font_choices',
            field=models.JSONField(blank=True, default=dict, help_text='Selected font families: {heading, body}.'),
        ),
        migrations.AddField(
            model_name='restauranttheme',
            name='landing_variant',
            field=models.CharField(choices=[('signature', 'Signature'), ('classic', 'Classic'), ('gastronomique', 'Deco'), ('editorial', 'Editorial'), ('botanica', 'Botanica'), ('cinematic', 'Cinema'), ('reel', 'Reel')], default='signature', max_length=20),
        ),
        migrations.AlterField(
            model_name='restauranttheme',
            name='ui_theme',
            field=models.CharField(choices=[('warm', 'Warm'), ('hybrid', 'Hybrid'), ('brutalist', 'Brutalist'), ('editorial', 'Editorial'), ('table-theory', 'Table Theory')], default='warm', max_length=20),
        ),
    ]
