// AUTO-GENERATED by scripts/fetch-videos.mjs — do not edit by hand.
import type { Rendition } from '../lib/pickRendition'

export const RENDITIONS: Record<string, Rendition[]> = {
  "hero": [
    {
      "height": 1080,
      "src": "/assets/video/hero-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/hero-720.mp4"
    },
    {
      "height": 360,
      "src": "/assets/video/hero-360.mp4"
    }
  ],
  "beverages": [
    {
      "height": 1080,
      "src": "/assets/video/beverages-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/beverages-720.mp4"
    },
    {
      "height": 360,
      "src": "/assets/video/beverages-360.mp4"
    }
  ],
  "soups": [
    {
      "height": 1080,
      "src": "/assets/video/soups-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/soups-720.mp4"
    },
    {
      "height": 360,
      "src": "/assets/video/soups-360.mp4"
    }
  ],
  "quickbites": [
    {
      "height": 1080,
      "src": "/assets/video/quickbites-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/quickbites-720.mp4"
    },
    {
      "height": 360,
      "src": "/assets/video/quickbites-360.mp4"
    }
  ],
  "italian": [
    {
      "height": 1080,
      "src": "/assets/video/italian-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/italian-720.mp4"
    },
    {
      "height": 360,
      "src": "/assets/video/italian-360.mp4"
    }
  ],
  "desserts": [
    {
      "height": 1080,
      "src": "/assets/video/desserts-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/desserts-720.mp4"
    }
  ],
  "waiter": [
    {
      "height": 1080,
      "src": "/assets/video/waiter-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/waiter-720.mp4"
    }
  ],
  "water": [
    {
      "height": 1080,
      "src": "/assets/video/water-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/water-720.mp4"
    },
    {
      "height": 360,
      "src": "/assets/video/water-360.mp4"
    }
  ],
  "bread": [
    {
      "height": 1080,
      "src": "/assets/video/bread-1080.mp4"
    },
    {
      "height": 720,
      "src": "/assets/video/bread-720.mp4"
    },
    {
      "height": 360,
      "src": "/assets/video/bread-360.mp4"
    }
  ]
}
