import { type MenuItem, getCategoryForItem } from './menu'
import { RENDITIONS } from './videoRenditions'
import type { Rendition } from '../lib/pickRendition'

// Surface keys that exist in RENDITIONS (auto-generated by scripts/fetch-videos.mjs):
// hero, beverages, soups, quickbites, italian, desserts, waiter, water, bread.
const HERO = 'hero'

// Maps category ID → banner filename (shared with CategoryPage).
export const BANNER_FILE: Record<string, string> = {
  beverages: 'beverages-banner.webp',
  soups: 'soups-banner.webp',
  quickbites: 'quickbites-banner.webp',
  italian: 'italian-banner.webp',
  desserts: 'dessert-banner.webp',
}

// Tag → curated category clip, for per-dish thematic variety (a cold drink uses
// the beverages clip, a warm dish the soups clip, an indulgent one desserts).
const TAG_VIDEO: Record<string, string> = {
  cold: 'beverages',
  refreshing: 'beverages',
  fizzy: 'beverages',
  warm: 'soups',
  spiced: 'soups',
  hot: 'soups',
  indulgent: 'desserts',
  creamy: 'desserts',
}

// Per-dish override — set when a specific dish gets its own clip later.
const ITEM_VIDEO_OVERRIDE: Record<string, string> = {}

interface ResolvedVideo {
  renditions: Rendition[]
  poster: string
}

/** Renditions for a surface key, falling back to the hero clip. */
export function videoRenditions(key: string): Rendition[] {
  return RENDITIONS[key] ?? RENDITIONS[HERO] ?? []
}

function dishKey(item: MenuItem): string {
  const override = ITEM_VIDEO_OVERRIDE[item.id]
  if (override) return override

  const tagHit = item.tags.map(t => TAG_VIDEO[t.toLowerCase()]).find(Boolean)
  if (tagHit) return tagHit

  const catId = getCategoryForItem(item.id)
  return RENDITIONS[catId] ? catId : HERO
}

/** Card thumbnail video — poster is the existing dish thumb. */
export function resolveDishVideo(item: MenuItem): ResolvedVideo {
  return { renditions: videoRenditions(dishKey(item)), poster: `/assets/dishes/${item.id}.webp` }
}

/** Detail hero video — poster is the existing dish hero still. */
export function resolveDishHeroVideo(item: MenuItem): ResolvedVideo {
  return { renditions: videoRenditions(dishKey(item)), poster: `/assets/dishes/${item.id}-hero.webp` }
}

/** Category banner video — poster is the existing banner. */
export function resolveCategoryVideo(catId: string): ResolvedVideo {
  const key = RENDITIONS[catId] ? catId : HERO
  const banner = BANNER_FILE[catId] ?? `${catId}-banner.webp`
  return { renditions: videoRenditions(key), poster: `/assets/covers/${banner}` }
}
