# Generated by Django 4.2.16 on 2026-06-03 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_identity_seed'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(choices=[('guest', 'Guest'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='new', max_length=12)),
                ('subtotal_minor', models.IntegerField(default=0)),
                ('discount_pct', models.PositiveSmallIntegerField(default=0)),
                ('tax_minor', models.IntegerField(default=0)),
                ('total_minor', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('voided', models.BooleanField(default=False)),
                ('comp', models.BooleanField(default=False)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('item_name', models.CharField(max_length=160)),
                ('unit_price_minor', models.IntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('seat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ops.order')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('seats', models.PositiveSmallIntegerField(default=2)),
                ('zone', models.CharField(choices=[('Garden', 'Garden'), ('Indoor', 'Indoor'), ('Patio', 'Patio'), ('Bar', 'Bar')], default='Indoor', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('seated', 'Seated'), ('ordering', 'Ordering'), ('bill-requested', 'Bill requested'), ('needs-attention', 'Needs attention')], default='available', max_length=20)),
                ('guests', models.PositiveSmallIntegerField(default=0)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('waiter_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='accounts.membership')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(max_length=120)),
                ('price_delta_minor', models.IntegerField(default=0)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_line_modifiers', to='menu.modifier')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='ops.orderline')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ops.restauranttable'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.membership'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(choices=[('void', 'Void'), ('comp', 'Comp'), ('discount', 'Discount'), ('merge', 'Merge'), ('transfer', 'Transfer'), ('price-change', 'Price change'), ('role-change', 'Role change')], max_length=16)),
                ('table_id', models.UUIDField(blank=True, null=True)),
                ('amount_minor', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='accounts.membership')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='ops.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('waiter', 'Waiter'), ('water', 'Water'), ('bill', 'Bill'), ('assistance', 'Assistance'), ('cleanup', 'Cleanup')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('claimed_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_requests', to='accounts.membership')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ops.restauranttable')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['restaurant_id', '-created_at'], name='ops_req_pending_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('restaurant_id', 'code'), name='uniq_table_restaurant_code'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['new', 'preparing', 'ready'])), fields=['restaurant_id', 'table'], name='ops_order_open_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant_id', '-placed_at'], name='ops_order_restaur_7abaec_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('restaurant_id', 'code'), name='uniq_order_restaurant_code'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['restaurant_id', '-created_at'], name='ops_auditlo_restaur_ce0379_idx'),
        ),
    ]
