# Generated by Django 4.2.16 on 2026-06-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_confirmation', 'Pending confirmation'), ('confirmed', 'Confirmed')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dining.guestdevice'),
        ),
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dining.diningsession'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='dining.guestdevice'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('session', 'idempotency_key'), name='uniq_order_session_idempotency_key'),
        ),
    ]
