# Generated by Django 4.2.16 on 2026-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_order_confirmation_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='type',
            field=models.CharField(choices=[('void', 'Void'), ('comp', 'Comp'), ('discount', 'Discount'), ('merge', 'Merge'), ('transfer', 'Transfer'), ('price-change', 'Price change'), ('role-change', 'Role change'), ('payment', 'Payment'), ('dispute', 'Dispute')], max_length=16),
        ),
    ]
