# Generated by Django 4.2.16 on 2026-06-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_auditlog_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(fields=('restaurant_id', 'code'), name='uniq_request_restaurant_code'),
        ),
    ]
